export const projects = [
  {
    id: 10,
    title: "Petscue",
    description:
      "Petscue is a full-stack web application, my bootcamp's final project, aimed at facilitating responsible animal adoption. It securely connects rescuers, former owners, and potential adopters. The app enables rescuers to publish animal details and manage requests, allows former owners to find new homes, and lets adopters create profiles, browse available animals, favorite them, and communicate with caregivers. This comprehensive platform streamlines the adoption process with a robust backend and intuitive frontend ",
    longDescription: "More detailed description of the project",
    technologies: [
      "ReactJS",
      "JavaScript",
      "HTML5",
      "CSS3",
      "Bootstrap 5",
      "Python 3",
      "Flask",
      "SQL",
      "SQLAlchemy",
      "Cloudinary",
      "Flask Mail"
    ],
    image: "/petscue-portfolio.png",
    github: "https://github.com/Alisoneoz/latam-pt-46-Petscue",
    live: "https://sample-service-name-8c9f.onrender.com",
    featured: true,
    category: "fullstack",
  },
  {
    id: 11,
    title: "Playing with ThreeJS",
    description:
      "This project brings 3D interactivity to the web using Three.js and React-Three/Drei, all within a Next.js and Tailwind CSS setup. It features real-time manipulation of Blender-created models, dynamic animations, and smooth scene controls. Along the way, I also explored how AI tools like PearAI can support the development process, especially when tackling complex integration challenges across technologies.",
    longDescription: "More detailed description of the project",
    technologies:[
      "React.js",
      "Next.js",
      "Three.js",
      "React Three Fiber",
      "Drei",
      "Tailwind CSS",
      "Framer Motion",
      "Blender",
      "Leva", 
      "PearAI (AI-powered Code Editor)" 
    ],
    image: "/threejs-portfolio.png",
    github: "https://github.com/Alisoneoz/3D-Landing-Page",
    live: "https://practicing-threejs.netlify.app",
    featured: true,
    category: "fullstack",
  },
  {
    id: 1,
    title: "DEMO: E-commerce Clothing Store",
    description:
      "A fully functional demo e-commerce website featuring user authentication powered by Firebase and integrates Stripe Checkout for a seamless payment experience. The homepage showcases a diverse range of products, with clear descriptions and pricing. Users can easily add items to their cart, offering a streamlined shopping experience. ",
    longDescription: "More detailed description of the project",
    technologies: [
      "ReactJS",
      "ViteJS",
      "Redux Toolkit",
      "TailwindCSS",
      "ExpressJS",
      "Stripe",
      "Firebase Auth",
      "Axios",
    ],
    image: "/dragonEcommerce.webp",
    github: "https://github.com/Alisoneoz/Dragon-ecommerce",
    live: "https://dragon-ecommerce-store.netlify.app/",
    featured: true,
    category: "fullstack",
  },
  {
    id: 8,
    title: "To-Do List Web App",
    description:
      "The To-Do app is built with the MERN stack and features user authentication, allowing users to create accounts for managing their tasks. It enables users to create, edit, display, and delete tasks, with all entries saved specifically for their accounts. Key features include custom user authentication using JSON Web Tokens, as well as the ability to switch between dark and light modes. The app is designed to be responsive, ensuring a seamless experience across both mobile and desktop devices.",
    longDescription: "More detailed description of the project",
    technologies: [
      "React JS",
      "ViteJS",
      "TailwindCSS",
      "NodeJS",
      "Express JS",
      "Mongoose",
      "MongoDB",
    ],
    image: "/todoApp.webp",
    github: "https://github.com/Alisoneoz/todo-mern-app",
    live: "https://todo-mern-app-alisoneoz.netlify.app/",
    featured: true,
    category: "fullstack",
  },
  {
    id: 9,
    title: "Nutri-Converter",
    description:
      "Web app designed with a Spanish user interface that helps users convert nutritional information based solely on macronutrients into diabetic exchange equivalents. Users can input the macronutrient data of their food items, and the app calculates how many exchanges these portions represent, making it easier for those managing diabetes to understand their dietary options. With its user-friendly design, Nutri-Converter enables users to make informed choices about their food intake based on macronutrient values.",
    longDescription: "More detailed description of the project",
    technologies: ["React JS", "ViteJS", "TailwindCSS", "MathJS"],
    image: "/nutriConverter.webp",
    live: "https://nutri-convertidor-alison-estephany.netlify.app/",
    featured: true,
    category: "FrontEnd",
  },
  {
    id: 7,
    title: "Alison Estephany Nutrición",
    description:
      "Designed for busy individuals, this Spanish-language website provides practical nutrition guidance with sections for services, contact, and a helpful blog. Users can explore consultation packages, read client testimonials, and get to know the expert behind the guidance, fostering trust and transparency. A contact form allows for easy inquiries, and the blog offers valuable tips for a healthier lifestyle",
    longDescription: "More detailed description of the project",
    technologies: ["WordPress", "Elementor"],
    image: "/AlisonEstephanyNutricion.webp",
    live: "https://alisonestephany.com/",
    featured: true,
    category: "WordPress",
  },
  {
    id: 2,
    title: "Latina Media",
    description:
      "This project is a website created for an online marketing and social media agency. It's designed with user-friendly navigation, featuring integrated options for booking brand consulting sessions via WooCommerce and scheduling appointments through Calendly. The responsive layout, vibrant imagery, and clear calls-to-action ensure an engaging experience while effectively highlighting social media marketing services.",
    longDescription: "More detailed description of the project",
    technologies: ["WordPress", "Elementor", "WooCommerce", "Calendly", "CSS3"],
    image: "/Screenshot-2024-10-29T142058.638.webp",
    live: "https://latinamedia.nl/",
    featured: false,
    category: "WordPress",
  },
  {
    id: 3,
    title: "Remy’s Consulting",
    description:
      "With a user-friendly and responsive design, the website for Remy’s Consulting, a firm focused on funding consulting services for nonprofits their unique offerings, con contains key pages like Services, About, and Contact to guide users through the firm’s approach, making it easy for potential clients to understand services and book consultations.",
    longDescription: "More detailed description of the project",
    technologies: ["WordPress", "Elementor"],
    image: "/Screenshot - 2024-10-29T162423.059.webp",
    live: "https://remysconsulting.com/",
    featured: true,
    category: "WordPress",
  },

  {
    id: 4,
    title: "Bare Skyn Beauty Bar",
    description:
      "Designed for esthetician Cherish Brown, this website features an inviting, user-friendly layout with dedicated sections for services, booking, events, and contact information. It highlights offerings like facials, body treatments, and waxing, with easy navigation for scheduling appointments. Social media links and a mailing list subscription are integrated",
    longDescription: "More detailed description of the project",
    technologies: ["Wix", "Wix Editor"],
    image: "/Captura-de-pantalla-2024-10-28-213326.webp",
    live: "https://www.bareskynbb.com/",
    featured: false,
    category: "Wix",
  },
  {
    id: 5,
    title: "Liam Clayton Sound",
    description:
      "This website for sound engineer Liam Clayton features a clean, professional layout with sections for portfolio, services, blog, and contact. The site offers streamlined navigation, showcasing Liam's audio projects across TV, film, and online media, with quick access to his expertise. A blog section provides additional insights, while integrated social media links allow for easy connectivity.",
    technologies: ["Wix", "Wix Editor"],
    image: "/Screenshot-2024-10-28T212954.523.webp",
    live: "https://www.liamclaytonsound.com/",
    featured: false,
    category: "Wix",
  },

  {
    id: 6,
    title: "Lili Gray Consulting",
    description:
      "This redesign for Lili Gray Consulting highlights a structured layout that organizes key mental health training services and professional development offerings. Clear navigation directs users to services, while a contact form supports streamlined inquiry and consultation scheduling. The design combines a professional and approachable aesthetic inspired by the Lili's passion for flowers, tailored for mental health professionals seeking specialized training and consultancy",
    longDescription: "More detailed description of the project",
    technologies: ["Squarespace", "CSS3", "JavaScript"],
    image: "/liliGray.webp",
    live: "https://www.liligrayconsulting.com/",
    featured: false,
    category: "Squarespace",
  },
];
